server:
  port: 8081

spring:
  application:
    name: book-reviews-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_service
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        hibernate:
          timezone:
            default_storage: NORMALIZE
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
  liquibase:
    change-log: classpath:liquibase/changelog.yml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 60000
            readTimeout: 60000
            loggerLevel: basic

management:
  server:
    port: 80
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - prometheus
  metrics:
    tags:
      application: ${spring.application.name}

google:
  api:
    host: https://www.googleapis.com
    url: /books/v1/volumes
    key: AIzaSyArFjKjsuaNWe_s1rAtMnIkG2mcEFfVdY8