version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "Installing dependencies..."
      - if [ ! "$(command -v docker)" ]; then apt-get update && apt-get install -y docker.io; fi

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Starting pre-build phase..."

  build:
    commands:
      - echo "Building Docker image..."
      - docker-compose -f CI-CD/docker-compose.yaml build
      - docker-compose -f CI-CD/docker-compose.yaml push

  post_build:
    commands:
      - echo "Build completed on `date`"
