version: "3.5"

services:

  db:
    image: postgres:14-alpine
    restart: always
    hostname: db
    container_name: db
    environment:
      POSTGRES_USER: $AND_DB_USER
      POSTGRES_PASSWORD: $AND_DB_PASS
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_databases.sql
    ports:
      - "5432:5432"
    networks:
      - book-reviews-service-net

  book-review-service:
    hostname: book-reviews-service
    container_name: book-reviews-service
    build:
      context: ..
      dockerfile: Dockerfile
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/book-review-service:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_USERNAME: $AND_DB_USER
      SPRING_DATASOURCE_PASSWORD: $AND_DB_PASS
      SPRING_DATASOURCE_URL: $AND_DB_URL
      SPRING_LIQUIBASE_USERNAME: $AND_DB_USER
      SPRING_LIQUIBASE_PASSWORD: $AND_DB_PASS
      SPRING_LIQUIBASE_URL: $AND_DB_URL
    networks:
      - book-reviews-service-net

networks:
  book-reviews-service-net:
    name: book-local
    driver: bridge

volumes:
  db_data: